const htmlEntities = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;'
};

const escapeHTML = value => {
    return String(value ?? '').replace(/[&<>"']/g, character => htmlEntities[character]);
};

const githubProfileUrl = username => {
    return `https://github.com/${encodeURIComponent(String(username ?? '').trim())}`;
};

const mailtoUrl = email => {
    return `mailto:${encodeURIComponent(String(email ?? '').trim())}`;
};

const renderEmail = email => {
    return `<a href="${escapeHTML(mailtoUrl(email))}">${escapeHTML(email)}</a>`;
};

const ROLE_META = {
    Manager:  { tag: 'M-01', color: '#d9594c' },
    Engineer: { tag: 'E-02', color: '#3a8a72' },
    Intern:   { tag: 'I-03', color: '#c79235' }
};

const renderField = (label, value) => `
                <div class="field">
                    <dt>${escapeHTML(label)}</dt>
                    <dd>${value}</dd>
                </div>`;

const renderCard = (employee, role, extraField) => {
    const meta = ROLE_META[role];
    return `
        <article class="card" style="--accent: ${meta.color};">
            <header class="card-head">
                <span class="card-tag">${meta.tag}</span>
                <h2 class="card-name">${escapeHTML(employee.name)}</h2>
                <p class="card-role">${escapeHTML(role)}</p>
            </header>
            <dl class="card-body">${renderField('ID', escapeHTML(employee.id))}${renderField('Email', renderEmail(employee.email))}${extraField}
            </dl>
        </article>`;
};

const generateManager = manager =>
    renderCard(manager, 'Manager', renderField('Office', escapeHTML(manager.officeNumber)));

const generateEngineer = engineer =>
    renderCard(
        engineer,
        'Engineer',
        renderField(
            'GitHub',
            `<a href="${escapeHTML(githubProfileUrl(engineer.github))}">${escapeHTML(engineer.github)}</a>`
        )
    );

const generateIntern = intern =>
    renderCard(intern, 'Intern', renderField('School', escapeHTML(intern.school)));

const ROLE_RENDERERS = {
    Manager: generateManager,
    Engineer: generateEngineer,
    Intern: generateIntern
};

const generateTeamPage = employeeCards => `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Team Profile</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header class="masthead">
        <div class="masthead-rule"></div>
        <div class="masthead-row">
            <span class="masthead-meta">Personnel Dossier</span>
            <h1 class="masthead-title">Team Profile</h1>
            <span class="masthead-meta masthead-date">${new Date().toLocaleDateString('en-US', {
                year: 'numeric', month: 'long', day: '2-digit'
            })}</span>
        </div>
        <div class="masthead-rule"></div>
    </header>
    <main class="roster">
${employeeCards}
    </main>
    <footer class="colophon">
        <span>Generated by Team Profile Generator</span>
        <span>· · ·</span>
        <span>Internal Use</span>
    </footer>
</body>
</html>
`;

const generateHTML = data => {
    const cards = data
        .map(employee => {
            const role = employee.getRole();
            const renderer = ROLE_RENDERERS[role];
            return renderer ? renderer(employee) : '';
        })
        .filter(Boolean)
        .join('\n');

    return generateTeamPage(cards);
};

module.exports = generateHTML;
